<div class="archive"> 
	<ul>
		<h2><strong>General Articles</strong></h2><br>
		<li class="widget-container widget_recent_news ititle">Evaluating the performance and intellectual structure of biogas research in China during 2000-2015<p class="iauthor"> &mdash; Lie Yang, Tiantian Sun, Yanli Liu, Zhulei Chen, Houqing Guo, Huan Chen, Haoqian Wang, Zhan Wu, Yingxuan Miu, Lixin Lv, Jie Zhang and Chang Liu</p></li>
		<li class="widget-container widget_recent_news ititle">Spatio-temporal analysis of drought and aridity in Gomti basin<p class="iauthor"> &mdash; R. Sarma and D.K. Singh</p></li>
		<li class="widget-container widget_recent_news ititle">The role of technology in responding to disasters: insights from the great deluge in Kerala<p class="iauthor"> &mdash; Anamika Ajay</p></li>
		<li class="widget-container widget_recent_news ititle">Landsat 8 OLI data for identification of hydrothermal alteration zone in Singhbhum Shear Zone (SCZ) using successive band depth difference technique - a new image processing approach<p class="iauthor"> &mdash; Krishnendu Banerjee, Manish Kumar Jain, A.T. Jeyaseelan and Surajit Panda</p></li>
		<li class="widget-container widget_recent_news ititle">Dynamic pricing and markdown timing policies for fashion goods with strategic consumers' behavior<p class="iauthor"> &mdash; Yanli Fang, Xianping Wang, Weijing Wang and Ping Fan</p></li>
		<li class="widget-container widget_recent_news ititle">Transforming forestry education for better job prospects<p class="iauthor"> &mdash; Ayyanadar Arunachalam and Latika Pandey</p></li>
		<li class="widget-container widget_recent_news ititle">How much research output from India gets social media attention?<p class="iauthor"> &mdash; Sumit Kumar Banshal, Vivek Kumar Singh, Pranab K. Muhuri and Philipp Mayr</p></li>
		<li class="widget-container widget_recent_news ititle">Shifting paradigms: Why history matters in geological sciences<p class="iauthor"> &mdash; C.P. Rajendran</p></li>
		<li class="widget-container widget_recent_news ititle">Visualization analysis of research on rice with fertilizer from the ‘agronomy’ category based on Citespace<p class="iauthor"> &mdash; Jie Sun and Bao-Zhong Yuan</p></li>
		<li class="widget-container widget_recent_news ititle">Characterizing interdisciplinarity of Nobel Laureates’ key publications<p class="iauthor"> &mdash; Helena H. Zhang, Ruby W. Wang, Ronda J. Zhang and Fred Y. Ye</p></li>
		<li class="widget-container widget_recent_news ititle">India meteorological department: weather-ready, climate-smart<p class="iauthor"> &mdash; Rajeev Kumar Mehajan, Abha Tewary and Shreekant Gupta</p></li>
		<li class="widget-container widget_recent_news ititle">Need to firm up techno-legal definition of the Blue gold: the river floodplains in India<p class="iauthor"> &mdash; Vikram Soni, Shashank Shekhar and Vikrant Jain</p></li>
		<li class="widget-container widget_recent_news ititle">Normalization of marks in multi-session examinations<p class="iauthor"> &mdash; Abhay G. Bhatt, Sourish Das and Rajeeva. L. Karandikar</p></li>
		<li class="widget-container widget_recent_news ititle">Integrating the function of a university to a work place to promote post-academic research: a case study<p class="iauthor"> &mdash; R.B. Grover</p></li>
		<br>
		<h2><strong>Review Articles/Research Articles/Research Accounts/Research Communications</strong></h2><br>
		<li class="widget-container widget_recent_news ititle">Current scenario of air pollution in relation to respiratory health<p class="iauthor"> &mdash; H. Paramesh</p></li>
		<li class="widget-container widget_recent_news ititle">A tale of two eras (1973-2014). World energy scene - 40 years after energy crisis<p class="iauthor"> &mdash; B.G. Desai</p></li>
		<li class="widget-container widget_recent_news ititle">The study and necessity of "Infill" development in urban planning and management with an approach to preserve historical texture values(Case Study: Tajrish Square)<p class="iauthor"> &mdash; Jamal-e-Din Mahdi Nejad, Hamidreza Azemati and Ali Sadeghi HabibAbad</p></li>
		<li class="widget-container widget_recent_news ititle">Low cost hydroponic fodder production technology for sustainable livestock farming during fodder scarcity<p class="iauthor"> &mdash; S. Gunasekaran, C. Bandeswaran and C. Valli</p></li>
		<li class="widget-container widget_recent_news ititle">Development and characterization of commercial biodegradable films using blown film extrusion technology<p class="iauthor"> &mdash; S. Mangaraj, S. Mohanty, S. Swain and A. Yadav</p></li>
		<li class="widget-container widget_recent_news ititle">Benthic communities of mesophotic coral ecosystem off Pondicherry, the East Coast of India<p class="iauthor"> &mdash; P. Laxmilatha, S. Jasmine, Miriam Paul Sreeram and Periasamy Rengaiyan</p></li>
		<li class="widget-container widget_recent_news ititle">Effect of deoxycholate capped silver nanoparticles in seed dormancy breaking of <i>Withania somnifera</i><p class="iauthor"> &mdash; Raja Muthuramalingam Thangavelu, Bupesh Munisamy and Kathiravan Krishnan</p></li>
		<li class="widget-container widget_recent_news ititle">Challenges of hill farming due to crop-raiding by wild pigs in the Indian Himalayan region<p class="iauthor"> &mdash; Latika Pandey, Ayyanadar Arunachalam and Namita Joshi</p></li>
		<li class="widget-container widget_recent_news ititle">Dynamic soil-structure interaction effects on 3D integral railway bridge under high-speed moving loads<p class="iauthor"> &mdash; Anand M. Gharad and Ranjan S. Sonparote</p></li>
		<li class="widget-container widget_recent_news ititle">Evidence for underwater current activity on the upper slope of the carbonate platform off western India: study based on multibeam bathymetry<p class="iauthor"> &mdash; B. Chakraborty, V. Purnachandra Rao, Tejas Salkar, Vasudev P. Mahale and John Kurien</p></li>
		<li class="widget-container widget_recent_news ititle">Mineralogical transformations resulting from forest fire in the montane grassland systems of Southern Western Ghats, India<p class="iauthor"> &mdash; S. Sandeep, J.M. Ninu and K.A. Sreejith</p></li>
		<li class="widget-container widget_recent_news ititle">Commemorating 75 years of microemulsion: a journey forward<p class="iauthor"> &mdash; Animesh Kumar Rakshit, Bappaditya Naskar and Satya Priya Moulik</p></li>
		<li class="widget-container widget_recent_news ititle">Effects of elevated CO2 and temperature on rice brown planthopper, <i>Nilaparvata lugens</i> (Stål) populations in India<p class="iauthor"> &mdash; Sunil Vailla, Sampathkumar Muthusamy, Chiranjeevi Konijeti, Chitra Shanker and Jhansi Lakshmi Vattikuti</p></li>
		<li class="widget-container widget_recent_news ititle">Green protocol for the synthesis of 1,8-dioxo-decahydroacridines via Hantzsch condensation using citric acid as organocatalyst<p class="iauthor"> &mdash; Monika Patil, Shrikrishna Karhale, Ananda Kudale, Arjun Kumbhar, Sagar More and Vasant Helavi</p></li>
		<li class="widget-container widget_recent_news ititle">Limonene attenuates oxidative stress and extends longevity in <i>Caenorhabditis elegans</i><p class="iauthor"> &mdash; Pooja Shukla, Aakanksha Pant and Rakesh Pandey</p></li>
		<li class="widget-container widget_recent_news ititle">Efficacy of ascorbic acid treatments in production of green raisins<p class="iauthor"> &mdash; Prerna Nath, S.J. Kale and A.K. Sharma</p></li>
		<li class="widget-container widget_recent_news ititle">Occurrence of gem variety green sphalerite and dyscrasite in rocks of the Aravalli Supergroup, India<p class="iauthor"> &mdash; Shubhabrata Mukhopadhyay, Abhishek Anand and S.K. Rajput</p></li>
		<li class="widget-container widget_recent_news ititle">Crop stimulants as a factor determining the yield and quality of winter wheat grown in Notec Valley, Poland<p class="iauthor"> &mdash; Tomasz Knapowski, Bożena Barczak, Wojciech Kozera, Elżbieta Wszelaczyńska and Jarosław Pobereżny</p></li>
		<li class="widget-container widget_recent_news ititle">Prediction and verification of instability boundary for parallel hybrid electric vehicles during mode switches<p class="iauthor"> &mdash; Zhongyan Li, Donghai Hu and Leli Hu</p></li>
		<li class="widget-container widget_recent_news ititle">A real-time ICE on/off control strategy for hybrid electric bus based on route information prediction<p class="iauthor"> &mdash; Zhongyan Li and Lin Yang</p></li>
		<li class="widget-container widget_recent_news ititle">Evaluation of the decision-making process for urban public transport in India: a delphi approach<p class="iauthor"> &mdash; Nitin Lambat, Vijay Kapse and Chandra Sabnani</p></li>
		<li class="widget-container widget_recent_news ititle">Taming the Master: SWI/SNF chromatin remodeler as a therapeutic target in cancer<p class="iauthor"> &mdash; Murali Dharan Bashyam, Srinivas Animireddy and Pratyusha Bala</p></li>
		<li class="widget-container widget_recent_news ititle">Development of 90GHz microwave radiometer sensor in snow/ice studies over Himalayas as input for disaster monitoring<p class="iauthor"> &mdash; M.P. Vasudha, G. Raju and N. Thangadurai</p></li>
		<li class="widget-container widget_recent_news ititle">Large losses in glacier area and water availability by the end of the twenty-first century under high emission scenario, Sutlej Basin, Himalaya<p class="iauthor"> &mdash; Veena Prasad, Anil V. Kulkarni, S. Pradeep, S. Pratibha, Sayli A. Tawde, Tejal Shirsat, A.R. Arya, Andrew Orr and Daniel Bannister</p></li>
		<li class="widget-container widget_recent_news ititle">A GIS-based approach for radiation risk assessment around a thermal power plant towards adopting remedial measures<p class="iauthor"> &mdash; Kajori Parial, S. Mukherjee, A.R. Ghosh and D. Sengupta</p></li>
		<li class="widget-container widget_recent_news ititle">Photoluminescence and Raman studies of alpha-MoO3 doped with Erbium and Neodymium<p class="iauthor"> &mdash; M.R. Joya, J.E. Alfonso and L.C. Moreno</p></li>
		<li class="widget-container widget_recent_news ititle">Influential parameters for headed bars in RC beam-column joint: a review<p class="iauthor"> &mdash; Ajay Chourasia and Shipali Gupta</p></li>
		<li class="widget-container widget_recent_news ititle">Fishers‟ livelihood diversification in Bhagirathi-Hooghly stretch of Ganga river in India<p class="iauthor"> &mdash; Arun Pandit, Anjana Ekka, B.K. Das, S. Samanta, Lokenath Chakraborty and Rohan K. Raman</p></li>
		<li class="widget-container widget_recent_news ititle">Reducing wing observability to radar using microserrations at leading edge<p class="iauthor"> &mdash; Karri Sai Krishna Reddy and Avijit Chatterjee</p></li>
		<li class="widget-container widget_recent_news ititle">Numerical analysis of the gas-particle two-phase flow in a multistep dust collector<p class="iauthor"> &mdash; Jiafeng Yao, Zheng Wang, Minghao Yu, Yaoyao Wang, Bai Chen and Hongtao Wu</p></li>
		<li class="widget-container widget_recent_news ititle">A Laplace-transfer-based citation model and its application in detecting the obsolescence characteristics of articles<p class="iauthor"> &mdash; Mingyang Wang, Dongtian Leng, Yang Li and Xiangrong Zhang</p></li>
		<li class="widget-container widget_recent_news ititle">Biogenic silver nanoparticles adorned polyvinyl alcohol nanofibrous scaffolds avert tumor and bacterial growth<p class="iauthor"> &mdash; G.U. Preethi, B.S. Unnikrishnan, Manu M. Joseph, R. Shiji and T.T. Sreelekha</p></li>
		<li class="widget-container widget_recent_news ititle">Mineral-chemical perspective of Nain Ophiolite Mélange, Central Iran<p class="iauthor"> &mdash; Alireza Eslami, Jyotisankar Ray, Madhuparna Paul, Sonia Sarkar, Mousumi Banerjee, Moussa Noghreyan and Payel Dey</p></li>
		<li class="widget-container widget_recent_news ititle">Regional models assessing region specific determinants of low birth weight in India<p class="iauthor"> &mdash; Dharmendra Kumar Dubey and Dilip C. Nath</p></li>
		<li class="widget-container widget_recent_news ititle">On the recent floods in India<p class="iauthor"> &mdash; Kamaljit Ray, P. Pandey, C. Pandey, A.P. Dimri and K. Kishore</p></li>
		<li class="widget-container widget_recent_news ititle">Electrophysiological and behavioural responses of banana pseudostem weevil, <i>Odoiporus longicollis</i> Olivier (Coleoptera: Curculionidae) to aggregation pheromone, 2-methyl-4-heptanol and host plant kairomones<p class="iauthor"> &mdash; S. Palanichamy, B. Padmanaban, M. Mayil Vaganan and S. Uma</p></li>
		<li class="widget-container widget_recent_news ititle">Co-authorship network in cardiology research studies: case study of Iranian output<p class="iauthor"> &mdash; Eskrootchi Rogheyeh, Ashoori Mhranjani Forouzan, Shahrabi Farahani Helia and Mayank Yuvaraj</p></li>
		<li class="widget-container widget_recent_news ititle">Compound feed production for livestock: a technology review<p class="iauthor"> &mdash; D.J. Shrinivasa and S.M. Mathur</p></li>
		<li class="widget-container widget_recent_news ititle">The regulatory dilemma for import of radiopharmaceuticals in India: A case study<p class="iauthor"> &mdash; Sandeep Sharma, M.G.R Rajan, Ashish Baldi, Rajesh K. Singh and Rakesh Kumar Sharma</p></li>
		<li class="widget-container widget_recent_news ititle">Assessment of rainfall variability and its impact on groundnut yield in Bundelkhand region of India<p class="iauthor"> &mdash; Akram Ahmed, Dibyendu Deb and Surajit Mondal</p></li>
		<li class="widget-container widget_recent_news ititle">Confined masonry construction for India: a techno economical solution for improved seismic behaviour<p class="iauthor"> &mdash; Ajay Chourasia and Shubham Singhal</p></li>
		<li class="widget-container widget_recent_news ititle">Development of an efficient hierarchical clustering analysis using an agglomerative clustering algorithm<p class="iauthor"> &mdash; Arshia Naeem, Mariam Rehman, Maria Anjum and Malik Muhammad Asif</p></li>
		<li class="widget-container widget_recent_news ititle">Trends and insight of agroforestry practices in Madhya Pradesh, India<p class="iauthor"> &mdash; Arvind Bijalwan, Pooja Verma, Manmohan J.R. Dobriyal, A.K. Patil, Tarun Kumar Thakur and C.M. Sharma</p></li>
		<li class="widget-container widget_recent_news ititle">Serpentinized peridotite hosted polymetallic uranium mineralization (U-Cr-Ni-Mo-REE-Fe-Mg) in the vicinity of the Singhbhum shear zone, Kudada-Turamdih area, East Singhbhum district, Jharkhand: A new environment of Metallogeny in the Singhbhum Uranium Province of India<p class="iauthor"> &mdash; D.K. Sinha, Shekhar Gupta, K. Nautiyal, V.R. Akhila, V.K. Shrivastava, A.K. Padhi and M.B. Verma</p></li>
		<li class="widget-container widget_recent_news ititle">Analysis on the evolution game of the stakeholders’ behavior in the operation stage of green buildings<p class="iauthor"> &mdash; Xiaojun Liu and Xiaodan Liu</p></li>
		<li class="widget-container widget_recent_news ititle">Soil organic carbon (SOC) prediction using VNIR reflectance spectroscopy employing artificial neural network (ANN) modelling<p class="iauthor"> &mdash; K. Justin George, Suresh Kumar and R. Arya Raj</p></li>
		<li class="widget-container widget_recent_news ititle">Amelioration of bleomycin induced acute lung injury and epithelial-mesenchymal transition by baicalein in mice<p class="iauthor"> &mdash; Dheeraj Kumar Sharma, Nittin Dev Singh, Geeta Devi Leishangthem and Harmanjit Singh Banga</p></li>
		<li class="widget-container widget_recent_news ititle">A critical assessment of EIAs: a case study of Goa mines<p class="iauthor"> &mdash; Mandar N. Datar, Sujeet Dongre and Madhav Gadgil</p></li>
		<li class="widget-container widget_recent_news ititle">Analysing impact of major solar flares on ionospheric TEC using NavIC signals<p class="iauthor"> &mdash; Sonal Parmar, Upena Dalal and Kamlesh Pathak</p></li>
		<li class="widget-container widget_recent_news ititle">Ooid fabric in the Jurassic of the Indus Basin of Pakistan: control on the original mineralogy<p class="iauthor"> &mdash; Fahad Ali, Muhammad Hanif, Shiqi Zhang, Khalid Latif, Sajjad Ahmad, Irfan U. Jan and Hawas Khan</p></li>
		<li class="widget-container widget_recent_news ititle">Landslides mapped from satellite data in the Western Ghats of Indian Peninsula after the August 2018 excess rainfall<p class="iauthor"> &mdash; Tapas R. Martha, Priyom Roy, Kirti Khanna, K. Mrinalni and K. Vinod Kumar</p></li>
		<li class="widget-container widget_recent_news ititle">Boron measurement in tourmaline from the pegmatite veins, Simdega area, Chhotanagpur Gneissic Complex, Eastern India, using CAMECA-SXFive Electron Probe Micro Analyzer (EPMA)<p class="iauthor"> &mdash; Deepak Kumar, Dinesh Pandit, Abhinay Sharma and N.V. Chalapathi Rao</p></li>
		<li class="widget-container widget_recent_news ititle">Potential spreading risk of an invasive freshwater snail (<i>Pomacea canaliculata</i>) in freshwater habitats of Asia<p class="iauthor"> &mdash; Wasana de Silva, Te Cao, Zihao Wen, Xiaolin Zhang and Leyi Ni</p></li>
		<li class="widget-container widget_recent_news ititle">Diversity and ecological role of insect flower visitors in the pollination of mangroves from Indian Sundarban<p class="iauthor"> &mdash; Udipta Chakraborti, Bulganin Mitra and Kakali Bhadra</p></li>
		<li class="widget-container widget_recent_news ititle">Spatiotemporal variation of single-season rice phenology in the Three Gorges Reservoir Area, 1991-2010<p class="iauthor"> &mdash; Lei He and Ji-Long Chen</p></li>
		<li class="widget-container widget_recent_news ititle">Proton gradient regulator 5 (<i>gaPGR5</i>) of <i>Gossypium arboreum</i> enhances salt-stress tolerance in <i>Gossypium hirsutum</i><p class="iauthor"> &mdash; Muhammad Naveed Shahid, Adil Jamal, Sarfraz Kiani, Javed Iqbal Wattoo, Bushra Rashid and Tayyab Husnain</p></li>
		<li class="widget-container widget_recent_news ititle">Fold catastrophe analysis of constitutive model of cutting load<p class="iauthor"> &mdash; Chenxu Luo, Shuangxi Jing, Xiaoming Han and Junfa Leng</p></li>
		<li class="widget-container widget_recent_news ititle">Variation studies in surface micro morphology on seed coat and endosperm of <i>Ensete superbum</i> (Roxb.) Cheesman: a conservation concern species of India<p class="iauthor"> &mdash; V. Saroj Kumar, R. Jaishanker and A. Annamalai</p></li>
		<li class="widget-container widget_recent_news ititle">Research of hundred years on inversion polymorphism in <i>Drosophila</i><p class="iauthor"> &mdash; B.N. Singh</p></li>
		<li class="widget-container widget_recent_news ititle">Development of village system model for predicting and comparing the different interventions success<p class="iauthor"> &mdash; Rahi Jain, Bakul Rao and Satanand Mishra</p></li>
		<li class="widget-container widget_recent_news ititle">Effects of the inclusion compounds of 1-methylcyclopropene/α-cyclodextrin or 1-methyl-3-(2-methylcyclopropyl)-1-cyclopropene /Cu-β-cyclodextrin on the preservation of sweet cherry (Prunus avium L.)<p class="iauthor"> &mdash; Zhu Jinwei, Feng Jiangtao and Yan Wei</p></li>
		<li class="widget-container widget_recent_news ititle">Comparative study of wheat varieties under open farming and poplar based agroforestry system<p class="iauthor"> &mdash; Abhay Kumar, Virendra Singh, Swati Shabnam, P.R. Oraon and Sunita Kumari</p></li>
		<li class="widget-container widget_recent_news ititle">Physico-chemical, photocatalytic and cytotoxicity evaluation of <i>Annona muricata</i> L. fruit extract derived zinc oxide nanoparticles in comparison to the commercial chemical version<p class="iauthor"> &mdash; Ahlam Abdul Aziz, V.S. Shaniba, P.R. Jayasree and P.R. Manish Kumar</p></li>
		<li class="widget-container widget_recent_news ititle"><i>In vitro</i> regeneration of coconut plantlets from immature inflorescence<p class="iauthor"> &mdash; M. Shareefa, Regi J. Thomas, J.S. Sreelekshmi, M.K. Rajesh and Anitha Karun</p></li>
		<li class="widget-container widget_recent_news ititle">Construct validity maps and the NIRF 2019 ranking of colleges<p class="iauthor"> &mdash; Gangan Prathap</p></li>
		<li class="widget-container widget_recent_news ititle">Comparative implementation of the benchmark Dejong5 function using Flower Pollination Algorithm and the African Buffalo Optimization<p class="iauthor"> &mdash; Julius Beneoluchi Odili and A. Noraziah</p></li>
		<li class="widget-container widget_recent_news ititle">Enhancing the biosurfactant production by hypersaline <i>Bacillus amyloliquefaciens</i> SK27 using response surface methodology and genetic algorithm<p class="iauthor"> &mdash; Ruchira Malik and Savita Kerkar</p></li>
		<li class="widget-container widget_recent_news ititle">Soil bacterial diversity and its determinants in the riparian zone of the Lijiang River, China<p class="iauthor"> &mdash; Jing Wang, Dongmei Wang and Bin Wang</p></li>
		<li class="widget-container widget_recent_news ititle">Tropical tropopause layer characteristics observed at different scales over complete Indian region using INSAT-3D sounder measurements<p class="iauthor"> &mdash; A. Hemanth Kumar and M. Venkat Ratnam</p></li>
		<li class="widget-container widget_recent_news ititle">Exploring the modulatory effect of albumin on calcium phosphate crystallization<p class="iauthor"> &mdash; Priyadarshini, Devesh Raizada, Pragya Kumar, Tanya Singh, Trisha Pruthi, Abhishek Negi, Lokesh Nigam and Naidu Subbarao</p></li>
		<li class="widget-container widget_recent_news ititle">Study of fuel economy and emissions for converted plug-in parallel hybrid electric vehicle versus conventional diesel vehicle on standard driving cycles<p class="iauthor"> &mdash; Pritam Keshavdas Gujarathi, Varsha A. Shah and Makarand M. Lokhande</p></li>
		<li class="widget-container widget_recent_news ititle">First record of <i>Pyura gangelion</i> (Savigny, 1816) (Tunicata; Pyuridae) from the Persian Gulf<p class="iauthor"> &mdash; Amin Afzali, Majid Askari Hesni, Azad Teimori and Thomas Stach</p></li>
		<li class="widget-container widget_recent_news ititle">The more the merrier: dogs can assess quantities in food choice tasks<p class="iauthor"> &mdash; Arunita Banerjee and Anindita Bhadra</p></li>
		<li class="widget-container widget_recent_news ititle">Limited replication studies in functional magnetic resonance imaging (fMRI) research on taste and food<p class="iauthor"> &mdash; Andy Wai Kan Yeung</p></li>
		<li class="widget-container widget_recent_news ititle">Transfer of innovations: a case of working of patents in India<p class="iauthor"> &mdash; Vikram Singh and Kajal Chakraborty</p></li>
		<li class="widget-container widget_recent_news ititle">South Asian subtropical low-level jet: influence on the regional hydrology and aerosol optical depth<p class="iauthor"> &mdash; T.R. Anoop, C.K. Unnikrishnan, Karumuri Ashok, K.K. Ramachandran and T.N. Prakash</p></li>
		<li class="widget-container widget_recent_news ititle">The influence of the nutrient availability on the reproduction and offspring growth in an <i>Vicia grandiflora</i><p class="iauthor"> &mdash; Jeremi Kołodziejek</p></li>
		<li class="widget-container widget_recent_news ititle">A quantitative assessment of crop species diversity in shifting cultivation system of Eastern Himalayas<p class="iauthor"> &mdash; D.K. Pandey, P. Adhihuru, S. Vimla Devi, Shivani Dobhal, S.K. Dubey and T.S. Mehra</p></li>
		<li class="widget-container widget_recent_news ititle">Type A personality competitiveness component linked to increased cardiovascular risk is positively related to study addiction but not to study engagement<p class="iauthor"> &mdash; Paweł A. Atroszko and Bartosz Atroszko</p></li>
		<li class="widget-container widget_recent_news ititle">Imidacloprid efficacy against brown planthopper, <i>Nilaparvata lugens</i> under elevated carbon dioxide and temperature<p class="iauthor"> &mdash; Govindharaj Guru-Pirasanna-Pandi, Subhash Chander, Madan Pal Singh, P.S. Soumia and M. Sujithra</p></li>
		<li class="widget-container widget_recent_news ititle">Probabilistic analysis of seismic data for earthquake forecast in north-east India and its vicinity<p class="iauthor"> &mdash; Timangshu Chetia, Saurabh Baruah, Chandan Dey, Sangeeta Sharma and Santanu Baruah</p></li>
		<li class="widget-container widget_recent_news ititle">A brief account of the current status of enthalpy entropy compensation phenomenon<p class="iauthor"> &mdash; Satya Priya Moulik, Bappaditya Naskar and Animesh Kumar Rakshit</p></li>
		<li class="widget-container widget_recent_news ititle">An estimation of change in forest above ground carbon in Bhimbandh Wildlife Sanctuary between 2007 and 2016<p class="iauthor"> &mdash; Suman Sinha and Abhisek Santra</p></li>
		<li class="widget-container widget_recent_news ititle">Forest biometric parameter extraction using Unmanned Aerial Vehicle (UAV) to aid in forest inventory data collection<p class="iauthor"> &mdash; Kasturi Chakraborty, Victor Saikom, Suranjana B. Borah, Mamita Kalita, Chirag Gupta, Laishram Ricky Meitei, K.K. Sarma and P.L.N. Raju</p></li>
		<li class="widget-container widget_recent_news ititle">Determination of tolerable dose of litchi fruit considering reported hypoglycinA and MCPG (methylenecyclopropyl-glycine) contents through biochemical and histopathological evaluations in mice upon litchi consumption<p class="iauthor"> &mdash; Jyoti Tripathi, Nilantana Bandyopadhyay, Sachin N. Hajare, Surbhi Wadhawan, Haladhar Dev Sarma and Satyendra Gautam</p></li>
		<li class="widget-container widget_recent_news ititle">Establishing empirical correlation between sediment thickness and resonant frequency using HVSR for the Indo-Gangetic Plain<p class="iauthor"> &mdash; P. Anbazhagan, A. Janarthana Boobalan and H.S. Shaivan</p></li>
		<li class="widget-container widget_recent_news ititle">Revisiting participatory forest management in India<p class="iauthor"> &mdash; G. Dhanapal</p></li>
		<li class="widget-container widget_recent_news ititle">Green synthesis, characterization and biological activity of synthesized Ruthenium nanoparticles using fishtail fern, sago palm, rosy periwrinkle and holy basil<p class="iauthor"> &mdash; Pranshu K. Gupta, Kalluri V.S. Ranganath, Nawal K. Dubey and Lallan Mishra</p></li>
		<li class="widget-container widget_recent_news ititle">Sustainability improvement of traditional cropping system of Uttarakhand through intercropping with medicinal and aromatic plants (MAPs)<p class="iauthor"> &mdash; Madhulika Pandey, B.P. Nautiyal and Nirdesh Kumar</p></li>
		<li class="widget-container widget_recent_news ititle">Development of eco and textile industry friendly short statured hirsute cotton variety, Indica<p class="iauthor"> &mdash; V.T. Sundaramurthy</p></li>
		<li class="widget-container widget_recent_news ititle">Repository of fungal endophytes at VINSTROM, Chennai: waiting to be harnessed<p class="iauthor"> &mdash; T.S. Suryanarayanan</p></li>
		<li class="widget-container widget_recent_news ititle">The use of a Weather Forecast Model to identify suitable sites for new wind power plants in Karnataka<p class="iauthor"> &mdash; Anasuya Gangopadhyay, Radhika Kanase, Greeshma Mohan, Madhuparna Halder, Medha Deshpande, Parthasharathi Mukhopadhyay and J. Srinivasan</p></li>
		<li class="widget-container widget_recent_news ititle">Comparison of parametric and non-parametric methods for chlorophyll estimation based on high resolution UAV imagery<p class="iauthor"> &mdash; Gaurav Singhal, Babankumar Bansod, Lini Mathew, Jonali Goswami, B.U. Choudhury and P.L.N. Raju</p></li>
		<li class="widget-container widget_recent_news ititle">Textural variation in the crustal xenoliths in basic dykes, Western Deccan Volcanic Province, Maharashtra: evidence of partial melting and pyrometamorphism<p class="iauthor"> &mdash; Aishwarya N. Ghole, Tanuuja Marathe and Sudha Vaddadi</p></li>
		<li class="widget-container widget_recent_news ititle">Retrospection of research on dragonfly and damselfly (Odonata) between 1980 and 2017: a bibliometric review<p class="iauthor"> &mdash; L.Z Cao and C.X Hu</p></li>
		<li class="widget-container widget_recent_news ititle">Foldscope as a research tool in the diagnosis of fungal leaf spot diseases in Sikkim<p class="iauthor"> &mdash; Lhanjey P. Wangdi, Arpan Pradhan and Srijana Mangar</p></li>
		<li class="widget-container widget_recent_news ititle">The first encounter of <i>Fistulina hepatica</i> (Schaeff.) With. belonging to the family Fistulinaceae in Nagaland, India<p class="iauthor"> &mdash; Gloria Nyenthang, Asangla Kichu, Lydia Yeptho and T. Ajungla</p></li>
		<li class="widget-container widget_recent_news ititle">Synchronous pulsed flowering in passion flower (<i>Passiflora incarnata</i>)<p class="iauthor"> &mdash; Surender Goyal, Rosmi Reji, Siddharth S. Tripathi and Narayanasami Sathyamurthy</p></li>
		<li class="widget-container widget_recent_news ititle">Assessment of level of service for urban signalized intersections in India<p class="iauthor"> &mdash; Arpita Saha, Satish Chandra and Indrajit Ghosh</p></li>
		<li class="widget-container widget_recent_news ititle">Sink removal from digital elevation model – a necessary evil for hydrological analysis<p class="iauthor"> &mdash; Arabinda Sharma and K.N. Tiwari</p></li>
		<li class="widget-container widget_recent_news ititle">Mapping shallow sub-surface to identify sinkhole formation in urban areas using Ground Penetration Radar (GPR): a case study from Hyderabad<p class="iauthor"> &mdash; Anand K. Pandey, Jonti Gogoi and Prabha Pandey</p></li>
		<li class="widget-container widget_recent_news ititle">Spectral characteristics of Common Iora <i>Aegithina tiphia</i> vocalisations and their context-specific preferences<p class="iauthor"> &mdash; C. Divyapriya and P. Pramod</p></li>
		<li class="widget-container widget_recent_news ititle">Assessment of airborne microbial community during the Middle East dust storm in Indian cities<p class="iauthor"> &mdash; Vikas C. Ghattargi, Mani Garg, Sudeeksha Raina, Jovita D. Silva, Shrikant P. Pawar, Praveen Rahi and Yogesh S. Shouche</p></li>
		<li class="widget-container widget_recent_news ititle">Bibliometric analysis of international cooperation research in the field of biomass energy<p class="iauthor"> &mdash; Xiaorong He and Dejian Yu</p></li>
		<li class="widget-container widget_recent_news ititle">Raw water treatment with Cl2 and ClO2: Comparison of two major class of disinfection by-products formation<p class="iauthor"> &mdash; R.K. Padhi, Suja Subramanian and K.K. Satpathy</p></li>
		<li class="widget-container widget_recent_news ititle">Air pollution in Delhi: biomass energy and suitable environmental policies are sustainable pathway for health safety<p class="iauthor"> &mdash; C.B. Tripathi, Prashant Baredar and Lata Tripathi</p></li>
		<li class="widget-container widget_recent_news ititle">High protein rice in high yielding background, cv. Naveen<p class="iauthor"> &mdash; Krishnendu Chattopadhyay, Srigopal Sharma, Torit Baran Bagchi, Bimal Mohanty, Sushree Sibanee Sardar, Sutapa Sarkar and Onkar Nath Singh</p></li>
		<li class="widget-container widget_recent_news ititle">How unequal is rural Punjab? : empirical evidence from spatial income distribution<p class="iauthor"> &mdash; Bishwa Bhaskar Choudhary and Priyanka Singh</p></li>
		<li class="widget-container widget_recent_news ititle">Carbon sequestration potential of mango orchards of India<p class="iauthor"> &mdash; A.N. Ganeshamurthy, V. Ravindra and T.R. Rupa</p></li>
		<li class="widget-container widget_recent_news ititle">Is rubber monoculture banishing agrobiodiversity and happiness? evidences from shifting cultivation landscape of Tripura, North-East India<p class="iauthor"> &mdash; D.K. Pandey, P. Adhiguru, Uma Sah, N. Devachandra, S.K. Dubey and Chandra Deo</p></li>
		<li class="widget-container widget_recent_news ititle">Prediction of rock load emphasizing excavation damage in-situ rock caused by blasting in coal mines<p class="iauthor"> &mdash; Avinash Paul, Vemavarapu Mallika Sita Ramachandra Murthy, Amar Prakash and Ajoy Kumar Singh</p></li>
		<li class="widget-container widget_recent_news ititle">Development of optimal weight algorithm for efficient application of DTCWT for resolution enhancement of satellite images<p class="iauthor"> &mdash; Akanksha Garg, Deepak Murugan and Dharmendra Singh</p></li>
		<li class="widget-container widget_recent_news ititle">Fate and transport of microplastics from water sources<p class="iauthor"> &mdash; Monnisha Ganesan, Gobi Nallathambi and Seshachalam Srinivasalu</p></li>
		<li class="widget-container widget_recent_news ititle">Novel genetic lineage of <i>Zeugodacus caudatus</i> (Diptera: Tephritidae) detected with <i>mtCOI</i> gene analysis from India<p class="iauthor"> &mdash; Chandra S. Prabhakar, Anil, Jaipal S. Choudhary, Ravi S. Singh, S.N. Ray, Kalmesh Managanvi, Mona Kumari, Ashok B. Hadapad and Ramesh S. Hire</p></li>
		<li class="widget-container widget_recent_news ititle">Targeting transcription factors for plant disease resistance: shifting paradigm<p class="iauthor"> &mdash; Anirudha Chattopadhyay, Jyotika Purohit, Kapil K Tiwari and Rupesh Deshmukh</p></li>
		<li class="widget-container widget_recent_news ititle">Global research landscape of high-level researches in Geosciences based on highly cited papers<p class="iauthor"> &mdash; Yanlin Cui</p></li>
		<li class="widget-container widget_recent_news ititle">Utilization of mahua resources: traditional knowledge as a tool for sustainable management<p class="iauthor"> &mdash; H.T. Hegde, R.P. Gunaga, N.S. Thakur, J.B. Bhusara and R.L. Soundarva</p></li>
		<li class="widget-container widget_recent_news ititle">The Sandan slot canyon in Deccan Traps: its morphology and mode of origin<p class="iauthor"> &mdash; Pramodkumar S. Hire, Archana D. Patil and Vishwas S. Kale</p></li>
		<li class="widget-container widget_recent_news ititle">Can Pigouvian taxation internalise the social cost of platinum-group element emissions?<p class="iauthor"> &mdash; Danuse Nerudova, Marian Dobranschi and Vojtech Adam</p></li>
		<li class="widget-container widget_recent_news ititle">A hybrid-wavelet artificial neural network (WANN) model for monthly water table depth prediction<p class="iauthor"> &mdash; Anandakumar, A.R. Senthil Kumar, Ravindra Kale and Prasad S. Kulkarni</p></li>
		<li class="widget-container widget_recent_news ititle">Green synthesis of silver nanoparticles using <i>Azadirachta indica</i> and <i>Ocimum sanctum</i> leaf extract: optimization of the process and anti-microbial activity against bacterial pathogens causing urinary tract infections<p class="iauthor"> &mdash; Sonali Priyadarshini, Sushree Sulava, Rasmita Bhol and Somanatha Jena</p></li>
		<br>
	</ul>
</div>